-- ============================================================
-- MODULE 10 — Payment Integrations
-- ============================================================

-- Payment gateway credentials per org
CREATE TABLE IF NOT EXISTS payment_integrations (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  provider        text NOT NULL CHECK (provider IN ('cakto','hotmart','doppus')),
  -- Cakto: webhook_token
  -- Hotmart: hottok, client_id, client_secret
  -- Doppus: api_key, webhook_secret
  credentials     jsonb NOT NULL DEFAULT '{}',
  is_active       boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE(organization_id, provider)
);

-- Payment links generated by IA or manually
CREATE TABLE IF NOT EXISTS payment_links (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  lead_id         uuid REFERENCES leads(id) ON DELETE SET NULL,
  product_id      uuid REFERENCES products(id) ON DELETE SET NULL,
  created_by_user uuid REFERENCES profiles(id) ON DELETE SET NULL,
  created_by_agent uuid,                    -- agent id that triggered gerar_link_pagamento
  provider        text NOT NULL CHECK (provider IN ('cakto','hotmart','doppus','manual')),
  external_id     text,                     -- checkout_id / offer_id from provider
  title           text NOT NULL,
  url             text NOT NULL,
  amount_cents    int,                      -- nullable for variable-price products
  currency        text NOT NULL DEFAULT 'BRL',
  status          text NOT NULL DEFAULT 'active' CHECK (status IN ('active','expired','paid','cancelled')),
  expires_at      timestamptz,
  metadata        jsonb NOT NULL DEFAULT '{}',
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- Payment transactions (events received from webhooks)
CREATE TABLE IF NOT EXISTS payment_transactions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  payment_link_id uuid REFERENCES payment_links(id) ON DELETE SET NULL,
  lead_id         uuid REFERENCES leads(id) ON DELETE SET NULL,
  provider        text NOT NULL,
  event_type      text NOT NULL,           -- compra_aprovada, reembolso, checkout_abandonado…
  external_id     text,                    -- provider transaction id
  amount_cents    int,
  currency        text NOT NULL DEFAULT 'BRL',
  status          text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','refunded','chargeback','abandoned')),
  buyer_name      text,
  buyer_email     text,
  buyer_phone     text,
  raw_payload     jsonb NOT NULL DEFAULT '{}',
  processed_at    timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- ── RLS ──────────────────────────────────────────────────────────────────────

ALTER TABLE payment_integrations  ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_links         ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_transactions  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "org members manage payment integrations"
  ON payment_integrations FOR ALL
  USING (organization_id = get_user_organization(auth.uid()))
  WITH CHECK (organization_id = get_user_organization(auth.uid()));

CREATE POLICY "org members manage payment links"
  ON payment_links FOR ALL
  USING (organization_id = get_user_organization(auth.uid()))
  WITH CHECK (organization_id = get_user_organization(auth.uid()));

CREATE POLICY "org members read transactions"
  ON payment_transactions FOR SELECT
  USING (organization_id = get_user_organization(auth.uid()));

-- Service role inserts from webhooks
CREATE POLICY "service role insert transactions"
  ON payment_transactions FOR INSERT
  WITH CHECK (true);

-- ── Indexes ───────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_payment_transactions_org
  ON payment_transactions(organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_lead
  ON payment_transactions(lead_id);

CREATE INDEX IF NOT EXISTS idx_payment_links_lead
  ON payment_links(lead_id);

CREATE INDEX IF NOT EXISTS idx_payment_links_org
  ON payment_links(organization_id, created_at DESC);

-- ── Updated_at ────────────────────────────────────────────────────────────────

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_payment_integrations_updated_at'
  ) THEN
    CREATE TRIGGER trg_payment_integrations_updated_at
      BEFORE UPDATE ON payment_integrations
      FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_payment_links_updated_at'
  ) THEN
    CREATE TRIGGER trg_payment_links_updated_at
      BEFORE UPDATE ON payment_links
      FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
  END IF;
END $$;
